name: Mermaid Diagram for PRs

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  generate-mermaid-diagram:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Generate Mermaid Diagram
        uses: gr2m/render-mermaid-action@v1
        with:
          input: diagram.mmd
          output: diagrams/diagram.png

      - name: Commit and Push Diagram to PR Branch
        uses: stefanzweifel/git-auto-commit-action@v5.0.0
        with:
          commit_message: "Automatically rendered Mermaid diagrams"
          file_pattern: "diagrams/*.png diagrams/*.svg"
          branch: ${{ github.head_ref }}

      - name: Upload Mermaid Diagram as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mermaid-diagram
          path: diagrams/diagram.png

      - name: Add Comment to PR with Mermaid Diagram
        run: |
          PR_BRANCH=${{ github.head_ref }}
          PR_IMAGE_URL="https://raw.githubusercontent.com/${{ github.repository }}/${PR_BRANCH}/diagrams/diagram.png"
          echo "ðŸ–¼ï¸ **Generated Mermaid Diagram for this PR:**" >> comment.md
          echo "![$PR_IMAGE_URL]($PR_IMAGE_URL)" >> comment.md

        uses: mshick/add-pr-comment@v2
        with:
          message-path: comment.md
